// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFxUBMHrgkAZ1lcIyg9HNh2j9CQ5CJFr8',
    appId: '1:392291622206:web:824ec6e94aad5493dee06f',
    messagingSenderId: '392291622206',
    projectId: 'databasedev-c56ad',
    authDomain: 'databasedev-c56ad.firebaseapp.com',
    databaseURL: 'https://databasedev-c56ad-default-rtdb.firebaseio.com',
    storageBucket: 'databasedev-c56ad.appspot.com',
    measurementId: 'G-WG6Q889G2Q',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwI0AUDZDviHC9Q2wo-Tyk-HwbaTAM9J8',
    appId: '1:392291622206:ios:5f111325b8872f96dee06f',
    messagingSenderId: '392291622206',
    projectId: 'databasedev-c56ad',
    databaseURL: 'https://databasedev-c56ad-default-rtdb.firebaseio.com',
    storageBucket: 'databasedev-c56ad.appspot.com',
    androidClientId: '392291622206-i8tbl85c7fpf9ml099s9heptcf6gl7bu.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );
}
